name: simple_ui
description: A simple Flutter UI

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  device_preview_plus: ^2.2.4
  dio: ^5.8.0+1
  easy_debounce: ^2.0.3
  easy_stepper: ^0.8.5+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_map: ^7.0.2
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  geolocator: ^13.0.2
  get: ^4.6.6
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  latlong2: ^0.9.1
  location: ^8.0.0
  retry: ^3.1.2
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.2"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/image.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/